config/routes.rb
Spree::Core::Engine.routes.draw do
	namespace :admin do
        resources :taxons do
        	resources :enhanced_banners, only: [:index, :new, :create, :destroy]
        	get :edit_config, :on => :member
        	patch :set, :on => :member
        end
        resource :enhanced_banner_settings, only: [:edit] do
        	post :save, :on => :member
        end
    end
end

app/models/spree/image_decorator.rb
Spree::Image.class_eval do
    attachment_definitions[:attachment][:styles] = {
      :mini => '48x48>', # thumbs under image
      :small => '100x100>', # images on category view
      :product => '240x240>', # full product image
      :large => '600x600>',  # light box image
      :banner => '800x200>', # banner image
      :banner_preview => '440x140>' # banner image
    }
  end

app/models/spree/taxon_banner_configuration.rb
class Spree::TaxonBannerConfiguration < ActiveRecord::Base
	belongs_to :taxon, :class_name => 'Spree::Taxon'

	validates :selection_mode, :presence => true
	validates :max_count, :presence => true, :numericality => { :only_integer => true,
  	                                   :greater_than_or_equal_to => 1 }

	before_validation :set_default_values_configuration

	protected

		def set_default_values_configuration
			if self.selection_mode.nil?
				self.selection_mode = "random"
			end
			self.max_count ||= 50
		end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
	has_one :taxon_banner_configuration, dependent: :destroy
	has_many :images, as: :viewable, dependent: :destroy

	protected
		def set_default_values_for_banner_configuration
			config = TaxonBannerConfiguration.create()
			config.taxon = self
		end
end

app/controllers/spree/admin/enhanced_banner_settings_controller.rb
module Spree
  module Admin
		class EnhancedBannerSettingsController < Spree::Admin::BaseController
			
			def edit
				@configuration = Spree::TaxonBannerConfiguration.new

				respond_to do |format|
					format.html
				end
			end

			def save
				respond_to do |format|
					begin
						Spree::TaxonBannerConfiguration.transaction do
							Spree::Taxon.all.each do |taxon|
								retrive_or_create(taxon)
								if params[:reset_indexes]
									@configuration.update_attribute(:last_index, 0)
								end
							end

							format.html { redirect_to edit_admin_general_settings_url, notice: 'Configuration was successfully saved.' }
						end
					rescue
						format.html { render action: "edit", notice: 'Set configuration failed.' }
					end
				end
			end

			private
				def config_params
					params.require(:taxon_banner_configuration).permit(:selection_mode, :max_count)
				end

				def retrive_or_create(taxon)
					if taxon.taxon_banner_configuration.nil?
						@configuration =  Spree::TaxonBannerConfiguration.new(config_params)
						@configuration.save
						taxon.taxon_banner_configuration = @configuration
					else
						@configuration =  Spree::TaxonBannerConfiguration.where(taxon_id: taxon.id).first
						@configuration.update_attributes(config_params)
					end
				end
		end
	end
end

app/controllers/spree/admin/enhanced_banners_controller.rb
module Spree
  module Admin
		class EnhancedBannersController < Spree::Admin::BaseController

			after_action :initialize_banner_configuration, only: [:create]

			def index
				@taxon = Spree::Taxon.find(params[:taxon_id])
				@banners = @taxon.images

				respond_to do |format|
					format.html
				end
			end

			def new
				@taxon = Spree::Taxon.find(params[:taxon_id])
				@image = Spree::Image.new

				respond_to do |format|
					format.html
				end
			end

			def create
				@taxon = Spree::Taxon.find(params[:taxon_id])
				@image = @taxon.images.build(image_params)

				respond_to do |format|
					if @image.save
						format.html { redirect_to admin_taxon_enhanced_banners_path(:taxon_id => @taxon.id), notice: 'Banner was successfully added.' }
					else
						@image = Spree::Image.new
						format.html { render action: "new", notice: 'Sorry, banner creation failed.' }
					end
				end
			end

			def destroy
				@image = Spree::Image.find(params[:id])
				@taxon = @image.viewable
				@banners = @taxon.images
				@image.destroy

				respond_to do |format|
		      format.html { render action: "index", notice: 'Banner was successfully removed.' }
		      format.js { render :partial => "spree/admin/shared/destroy", notice: 'Banner was successfully removed.' }
		    end
			end

			private
				def image_params
				  params.require(:image).permit(:attachment)
				end

				def initialize_banner_configuration()
					@taxon.taxon_banner_configuration ||= Spree::TaxonBannerConfiguration.create(:taxon_id => @taxon.id)
				end
		end
	end
end

app/controllers/spree/admin/taxons_controller_decorator.rb
Spree::Admin::TaxonsController.class_eval do

  def index
    @taxons = Spree::Taxon.all

    respond_to do |format|
    	format.html
    end
  end

  def edit_config
		@taxon = Spree::Taxon.find(params[:id])
		if @taxon.taxon_banner_configuration.nil?
			@configuration = Spree::TaxonBannerConfiguration.new
		else
			@configuration = @taxon.taxon_banner_configuration
		end

		respond_to do |format|
			format.html
		end
	end

	def set
		@taxon = Spree::Taxon.find(params[:id])			
		
		respond_to do |format|
			begin
				retrive_or_create(@taxon)
				if params[:reset_indexes]
					@configuration.update_attribute(:last_index, 0)
				end

				format.html { redirect_to admin_taxons_url, notice: 'Configuration was successfully seted.' }
			rescue
				@configuration = Spree::TaxonBannerConfiguration.new
				format.html { render action: "edit_config", notice: 'Set configuration failed.' }
			end
		end
	end

	private
		def config_params
			params.require(:taxon_banner_configuration).permit(:selection_mode, :max_count)
		end

		def retrive_or_create(taxon)
			if taxon.taxon_banner_configuration.nil?
				@configuration =  Spree::TaxonBannerConfiguration.new(config_params)
				@configuration.save
				taxon.taxon_banner_configuration = @configuration
			else
				@configuration =  Spree::TaxonBannerConfiguration.where(taxon_id: taxon.id).first
				@configuration.update_attributes(config_params)
			end
		end
end

app/helpers/spree/admin/enhanced_banner_helper.rb
module Spree
	module Admin
		module EnhancedBannerHelper
		end
	end
end

app/helpers/spree/admin/enhanced_banner_settings_helper.rb
module Spree
	module Admin
		module EnhancedBannerSettingsHelper
		end
	end
end

app/helpers/spree/base_helper_decorator.rb
Spree::BaseHelper.module_eval do

	def set_banner?(taxon)
		not taxon.nil? and taxon.images.count > 0
	end

	def get_banner_for_taxon(taxon)
		SelectionModeHelper.get_banner_for_taxon(taxon)
	end

	class SelectionModeHelper

		def self.get_banner_for_taxon(taxon)
			taxon_selection_mode = taxon.taxon_banner_configuration.selection_mode

			case(taxon_selection_mode)
				when "random" then self.get_banner_on_random_mode(taxon)
				when "cycle" then self.get_banner_on_cycle_mode(taxon)
			end
				
		end

		private
			def self.get_banner_on_random_mode(taxon)
				images = taxon.images
				random_index = SecureRandom.random_number(images.count)
				taxon.taxon_banner_configuration.update(last_index: random_index)
				images[random_index].attachment.url(:banner)
			end

			def self.get_banner_on_cycle_mode(taxon)
				images = taxon.images
				if (images.count - 1) == taxon.last_index
					taxon.taxon_banner_configuration.update(last_index: 0)
					next_index = taxon.taxon_banner_configuration.last_index
				else
					taxon.taxon_banner_configuration.update(last_index: taxon.taxon_banner_configuration + 1)
					next_index = taxon.taxon_banner_configuration.last_index
				end
				images[next_index].attachment.url(:banner)
			end
	end

	def link_to_configuration(url, options={})
		link_to_with_icon 'icon-cog', "Configuration", url, options
	end

	def link_to_banners(url, options={})
		link_to_with_icon 'icon-picture', "View Banners", url, options
	end
end

app/views/spree/admin/enhanced_banner_settings/_configuration_form.html.erb
<%= form_for @configuration, :url => save_admin_enhanced_banner_settings_path do |form|%>
	<div class="form-fields">
	 	<div class="field">
	 		<%= form.label :selection_mode, 'Mode' %>:
			<%= form.select(:selection_mode, options_for_select([['Random', 'random'], ['Cycle', 'cycle'], @configuration.selection_mode])) %>
	 	</div>
	 	<div class="field">
	 		<%= form.label :max_count, 'Max Count Banners' %>:
			<%= form.number_field :max_count, :min => 1 %>
	 	</div>
		<div class="field">
			<%= label_tag :reset_indexes, 'Reset Index?' %>:
			<%= check_box_tag(:reset_indexes) %>
		</div>
	</div>
	<div class="form-actions">
		<%= form.submit "Set Configuration" %>
	</div>
<% end %>

app/views/spree/admin/enhanced_banner_settings/_configuration_menu_items.html.erb
<%= configurations_sidebar_menu_item(t('enhanced_banner_settings'), edit_admin_enhanced_banner_settings_url) %>
<%= configurations_sidebar_menu_item(t('add_banner'), admin_taxons_url) %>

app/views/spree/admin/enhanced_banner_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  Configuration for all taxons
<% end %>

<%= render :partial => 'spree/admin/enhanced_banner_settings/configuration_form' %>

app/views/spree/admin/enhanced_banners/_form.html.erb
<%= form_for [:admin, @image], :url => admin_taxon_enhanced_banners_path(:taxon_id => @taxon.id), :html => { :multipart => true } do |form| %>
  <div class="form-fields">
  	<%= form.file_field :attachment %>
  </div>
  <div class="form-actions">
  	<%= form.submit "Add Banner" %>
  </div>
<% end %>

app/views/spree/admin/enhanced_banners/_list.html.erb
<div class="container-table" data-hook="admin-container-table-banners-taxon">
	<%if @banners.count == 0 %>
		<p>None banners added</p>
	<% else %>
		<table class="no-border-table">
			<% @banners.each do |banner| %>
				<tr>
					<td>
						<%= image_tag banner.attachment.url(:banner_preview) %>
					</td>
					<td class="actions">
						<%= link_to_delete banner, :url => admin_taxon_enhanced_banner_path(:taxon_id => @taxon.id, :id => banner.id), :no_text => true %>
					</td>
				</tr>
			<% end %>
		</table>
	<% end %>
</div>

app/views/spree/admin/enhanced_banners/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= @taxon.name %>'s Banners
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to "Add Banner", new_admin_taxon_enhanced_banner_path(:taxon_id => @taxon.id), :icon => 'icon-plus' %>
  </li>
  <li>
    <%= button_link_to "Back to taxons list", admin_taxons_url, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<div id='list-banners' data-hook>
  <%= render :partial => 'list' %>
</div>

app/views/spree/admin/enhanced_banners/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
	New Banner for <%= @taxon.name %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to "Back to taxon banners", admin_taxon_enhanced_banners_path(:taxon_id => @taxon.id), :icon => 'icon-arrow-left' %>
  </li>
  <li>
    <%= button_link_to "Back to taxons list", admin_taxons_url, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<div id='new-banner-form' data-hook>
  <%= render :partial => 'form' %>
</div>

app/views/spree/admin/taxons/_configuration_form.html.erb
<%= form_for @configuration, :url => set_admin_taxon_path(:id => @taxon.id, html: { method: "patch" }) do |form|%>
	<div class="form-fields">
	 	<div class="field">
	 		<%= form.label :selection_mode, 'Mode' %>:
			<%= form.select(:selection_mode, options_for_select([["Random", "random"], ["Cycle", "cycle"]], @configuration.selection_mode)) %>
	 	</div>
	 	<div class="field">
	 		<%= form.label :max_count, 'Max Count Banners' %>:
			<%= form.number_field :max_count, :min => 1 %>
	 	</div>
		<div class="field">
			<%= label_tag :reset_indexes, 'Reset Index?' %>:
			<%= check_box_tag(:reset_indexes) %>
		</div>
	</div>
	<div class="form-actions">
		<%= form.submit "Set Configuration" %>
	</div>
<% end %>

app/views/spree/admin/taxons/_list.html.erb
<div id="container-table" data-hook="admin-container-table-add-banner-taxon">
	<table class="taxon-table" data-hook="admin-table-add-banner-taxon">
		<thead>
		</thead>
		<tbody>
			<% @taxons.each do |taxon| %>
				<tr>
					<td class="big-col">
						<%= taxon.name %>
					</td>
					<td class="actions">
						<%= link_to_banners admin_taxon_enhanced_banners_path(:taxon_id => taxon.id), :no_text => true %>
						<%= link_to_configuration edit_config_admin_taxon_path(:id => taxon.id), :no_text => true %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/spree/admin/taxons/edit_config.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  Configuration for <%= @taxon.name %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to "Back to taxons list", admin_taxons_url, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/admin/taxons/configuration_form' %>

app/views/spree/admin/taxons/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  Taxons
<% end %>

<div id='list-banners' data-hook>
  <%= render :partial => 'list' %>
</div>

app/views/spree/shared/_message_errors.html.erb
<% if target.errors.any? %>
	<div id="error_explanation">
		<ul>
			<% target.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/spree/shared/_set_enhanced_banner.html.erb
<% if set_banner?(@taxon) %>
  <div class="columns sixteen">
  	<%= image_tag get_banner_for_taxon(@taxon) %>
  </div>
<% end %>